[package]
name = "flux"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "b9be7ff9-0e2e-42db-87bd-c6848a55c7ca"

[dependencies]
turbo = { version = "4.0.0", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
