name = "flux"
version = "0.1.0"
description = "An awesome game made in Turbo!"
authors = ["Enver Podgorcevic"]

[canvas]
width = 512
height = 288

[shader]
default-surface-shader = "my-awesome-shader"

[turbo-os]
api-url = "https://os.turbo.computer"